application: upitalks
module: present
version: none
runtime: go
api_version: go1

# from https://github.com/golang/talks/blob/master/app.yaml
handlers:
- url: /favicon.ico
  static_files: present/static/favicon.ico
  upload: present/static/favicon.ico
- url: /static
  static_dir: present/static
  application_readable: true
- url: /.*
  script: _go_app